### PR TITLE
Feature/multiroom

### PR DESCRIPTION
**Pull request by bramoosterhuis**
I tried to add some kind of multiroom/pipe configuration in the plugin.

### CODE REVIEW

**Comment by balbuze** [comment]
Thank you. I'll have a look on your code. But a work is in progress to do that for whole volumio source, not only volspotconnect.
If you want, we can talk about that on the gitter page https://gitter.im/balbuze/volumio-plugins?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge

**Comment by balbuze** [comment]
But as there no clear roadmap, maybe I will integrate your work waiting the other solution....

**Comment by Levdbas** [comment]
@balbuze , please do! I would love this feature in the volspot plugin!

**Comment by messismore** [comment]
@balbuze Is the effort to implement multi room playback coordinated anywhere?

**Pull request closed without merging**
