### PR TITLE
Add Natural Crossfeed

### PR DESCRIPTION
**Pull request by wbinek**
This pull request adds natural crossfeed based on "[Natural headphone crossfeed for foobar2000](https://www.head-fi.org/threads/natural-crossfeed-on-headphones-earphones-for-foobar2000-v2-1-major-update-made-public.811837/)"

The proposed crossfeed is based on HRTF functions created by Joseph Yeung. The set contains two versions of HRTFs (v1.1 and v2.1) for two different virtual speaker positions (30 deg and 50 deg). The HRTFs were modified to contain only the phase information for each channel and not to alter the amplitude part of the spectrum (as it should be done by the headphones).

According to the author of the original plugin:
"V1.1 should be a subtle effect, sound should be slightly more forward and the left-centre-right blobs effect of headphone soundstage should be alleviated. At no point should the soundstage feel constricted in width. Indeed the soundstage should continue to be a very enveloping experience and you may at times struggle to identify whether the crossfeed is slotted in or out.
V2.0 should yield an obvious out-of-your-head effect similar to listening to a genuine stereo setup. I find that the illusion grows on me especially through extended listening and especially if you sit in front of your computer monitor (the sounds will appear to come from and around the monitor)"

I know that some of the code is redundant, for example creating mixers almost identical to the ones from currently implemented crossfeeds, but I think the proposed solution is clearer than trying to reuse as much code as possible in some hacky way.

I haven't tested the modified install script, but the changes made are rather obvious and I hope they will work well.

### CODE REVIEW

**Comment by balbuze** [comment]
Thanks! I'll have a look on it. ;-)

**Comment by balbuze** [comment]
My comments.
1)- Filters are disgned only for 44100Hz. Camilla DSP as implented in the plugin is able to switch between samplerate but all filters must be provided for each sample rate. Then in CamillaDsp config we just send something like my-filter-$samplerate$.raw. when playing, samplerate is replaced by the correct value if the file exists.
2)- wav Can't be used as this due to the header. CamillaDsp is used with a input type file, it requires Raw data. When a wav file is selected as convolution filters in the plugin, it is converted to RAw.
So you have to convert your file using Sox or what you want.
Regards

**Comment by wbinek** [comment]
1) So which samplerates should be supported by default? Should we provide the HRTFs for all possible common samplerates? Isn't CamillaDsp resampling input or filters if they don't match?
2) I can provide the Raw files, but I think I am missing the point of it, as CamillaDsp supports .wav files. Could you please explain why we have to stick with raw files?

I have done some more experiments with HRTFs as crossfeed and I thought of another approach. Instead of providing a predefined set of HRTFs (as done in the commit), we can make an option to add custom HRTF (user would have to find the HRTF he/she wants to use in some database such as: [link](https://www.york.ac.uk/sadie-project/database.html) ). This would allow a user to find an HRTF that matches his own head best. 

The problem with such an approach is that we need to process the provided HRTFs to make them more even in terms of the amplitude response. Currently, I have a Matlab script that does (creates inverse, linear phase, FIR filter) it but it would need to be rewritten to Python(?), so it can be used locally on volumio host. It would require some work, but it may be beneficial. We can also resample the HRTFs during processing and create files for various samplerates. What do you think?

**Comment by balbuze** [comment]
Why no wav : https://github.com/HEnquist/camilladsp/blob/master/coefficients_from_wav.md
Samplerate switch : 

If the filename includes the tokens $samplerate$ or $channels$, these will be replaced by the corresponding values from the config. For example, if samplerate is 44100, the filename /path/to/filter_$samplerate$.raw will be updated to /path/to/filter_44100.raw.
from https://github.com/HEnquist/camilladsp
An other option would be to force sample rate using resampling in the plugin
I want to keep the plugin as easy as possible...
Sorry I can't tell you more now, I'm not at home...

**Comment by wbinek** [comment]
No problem, there is no hurry. I am sorry to ask so many questions, I just would like to make it work without going in some unwanted direction. Feel free to reply when you have time :)

I think the link you provided applies only to the input device (input stream). There is no problem with mixing raw input stream with FIR filter loaded from .wav. The CamillaDSP FIR filter documentation states "The type can be Raw, **Wav** or Values. Use Wav to load a standard .wav file,". Using wav files is beneficial as we can use stereo files and we don't have to worry about choosing the right data format. I strongly prefer using .wav files instead of .raw everywhere possible.

I understand the samplerate switching, I am just wondering which samplerates should we provide then, would 44100, 48000, 88200, 96000, 192000 be sufficient?

If the plugin is to be kept as easy as possible, I can preprocess the 20 measurements from SADIE II database and provide presets for each one. Then there can be one entry in the current crossfeeds list like "HRTF based crossfeed" and if chosen it would show a new list with HRTF presets to choose from.

**Comment by balbuze** [comment]
You're right for wav, I misunderstood or read to fast... Just need to skip header, often 44 first bytes, but Acourate header is 100 if I remember. But I have a routine for convolution filters selected by user. I'm going to reactivate it.
"44100, 48000, 88200, 96000, 192000 be sufficient?" for me yes.
If files are correctly name for samplerate switching, we can just add your 4 settings to the existing list.

**Comment by wbinek** [comment]
Sorry, it took so much time, the last week was busy for me. I have added the filters for samplerate switching and used tokens in the script. I have also replaced the Natural Crossfeed v2 filters with ones taken from the SADIE II database. The choice of HRTFs is however very subjective.

**Comment by balbuze** [comment]
I made some. It works! Well done.
I made some small modifications : hrtf-filters stay in the plugin folder, not in /INTERNAl. This because the scrolling list won't be updated if a user delete the folder and the result will be an entry with no effect or even CamillaDsp hang. But a nice add-on for FusionDsp! I'm very happy to see your interest for it! 
I'll try to publish this week end. Thanks

**Pull request merged**
