### PR TITLE
Bump Vollibrespot to v0.2.2

### PR DESCRIPTION
**Pull request by ashthespy**
Some small fixes [v0.2.2 - 2020-10-07](https://github.com/ashthespy/Vollibrespot/blob/master/CHANGELOG.md#022---2020-10-07), shouldn't break anything ;-)

### CODE REVIEW

**Comment by balbuze** [comment]
ready to test ;-)

**Comment by balbuze** [comment]
done but we need to fix the size of node_modules. If generated now, it exceed 11MB and volumio fails to install the plugin. The old one is <800kB...

**Comment by ashthespy** [comment]
I didn't add any new `node_modules`?

**Comment by balbuze** [comment]
Yes I know. It is just that some node dependencies changed and now a really bigger. I didn't analyse which one though. To be simple, I just kept old node modules instead of regenerated them.

**Pull request merged**
