### PR TITLE
[Volsptoconnect2] Better playback device management 

### PR DESCRIPTION
**Pull request by ashthespy**
#### Changes
1. Update config when playback device changes 
1. Re add the bitrate info - it is in alignment with the alsa output format that we use in the daemon.
1. Use default startup volume from Volumio instead of the UI slider. `UIConfig.json` needs updating if we want to remove the slider fully, or make it an optional parameter.
The only use case I can see still for the initial volume config option is  when there is no mixer set in Volumio, and so we fallback to internal software mixer. Do you think it would be better to expose the slider as a conditional configuration only for when mixer is set to none?

### CODE REVIEW

**Comment by balbuze** [comment]
Hi ash! Good job! Even if I didn't tested it yet! It could be a good thing to keep the initial volume in the case of no mixer. Ok for the nitrate display

**Comment by ashthespy** [comment]
I must confess, I don't have multiple playback outputs to check if the changes are updated, will try to test with HDMI/I2S/Onboard audio today. 
How is the best way to go for a conditional UI slider? Create a dummy value? Or just make a hidden "Advanced config" section?
Oh and also, can you also give me a sample of the `/tmp/vconfig.json` that is created for the loopback devices?

**Comment by balbuze** [comment]
A slider in advanced settings ask for "use Spotify software mixer" or something like that could be enough...
Vconfig is just a copy of /data/configuration/audio_interface/alsa_controller/config.json created when audio_interface plugin starts.

**Comment by ashthespy** [comment]
Ah okay!  What does the typical `outputdevice` look like when a loopback device is set by one of the `audio_interface` plugins? `Loopback:xx`? or? 
I will give it a go this evening :-)

**Comment by balbuze** [comment]
Hi!,
The output is set to "Loopback".

**Pull request merged**
