### PR TITLE
Add volspotconnect2 configurable bitrate

### PR DESCRIPTION
**Pull request by zewelor**

### CODE REVIEW

**Comment by ashthespy** [comment]
I think this option used to exist and then was removed (004b608168c1c153723302df05a3e02264e52e4a)
Might I ask the motivation for a lower bitrate - seems to go against the Volumio "Audiophile" player ideology if you ask me!

**Comment by zewelor** [comment]
Hi

Yes I saw it was removed, but without any info why. I've lowered bitrate for my summerhouse audio setup, as there is only 3g gsm, and lower bitrate works better on that connection. First I've just modified and hardcored lower bitrate value, but wanted to make it configurable and contribute upstream, maybe others will find it useable also ? I've left default 320 as it probably covers 99% of use cases :D

**Comment by zewelor** [comment]
@balbuze Is this change ok, or is there anything to change ? I can rebase for new release, if it will be accepted.

**Comment by balbuze** [comment]
hi!
yes, please update your pr with last version. If ok I'll merge it

**Comment by zewelor** [comment]
I've updated for the new code.

**Comment by balbuze** [comment]
small error line 542. Removed ";"
thanks!

**Comment by zewelor** [comment]
Great thanks !

**Pull request merged**
