### PR TITLE
[Volspotconnect2] Update `vollibrespot` to `0.1.8`

### LINKED ISSUE #238: No connection while playing podcast
Hello,

Volspotconnect 2 doesn't seem to work with the podcasts on Spotify, while it works for the songs.
Use case : I play music for a while with volumio, then I want to switch to a podcast. I choose the podcast, but it does'n start, the music still goes on and I'm unable to stop it. Seems like the connection between the server and client is not working after this. I have to restart the plugin so that it works again.

Thank you for the job anyway, it's a great plugin for Volumio.

Cheers

The logs are incredibly long, because the same operation repeats itself, so I cut it in the middle :

Jun 10 16:13:21 volumio volumio[1062]: [Vollibrespot] mdns::fsm: received question: IN Android.local
Jun 10 16:13:21 volumio volumio[1062]: [Vollibrespot] mdns::fsm: received question: IN Android.local
Jun 10 16:13:21 volumio volumio[1062]: [Vollibrespot] mdns::fsm: received question: IN Android.local
Jun 10 16:13:21 volumio volumio[1062]: [Vollibrespot] mdns::fsm: received question: IN Android.local
Jun 10 16:13:23 volumio volumio[1062]: [Vollibrespot] mdns::fsm: received question: IN _spotify-connect._tcp.local
Jun 10 16:13:24 volumio volumio[1062]: [Vollibrespot] mdns::fsm: received question: IN _spotify-connect._tcp.local
Jun 10 16:13:25 volumio volumio[1062]: [Vollibrespot] mdns::fsm: received question: IN Android.local
Jun 10 16:13:25 volumio volumio[1062]: [Vollibrespot] mdns::fsm: received question: IN Android.local
Jun 10 16:13:25 volumio volumio[1062]: [Vollibrespot] mdns::fsm: received question: IN Android.local
Jun 10 16:13:25 volumio volumio[1062]: [Vollibrespot] mdns::fsm: received question: IN Android.local
Jun 10 16:13:25 volumio volumio[1062]: [Vollibrespot] mdns::fsm: received question: IN Android.local
Jun 10 16:13:25 volumio volumio[1062]: [Vollibrespot] mdns::fsm: received question: IN Android.local
Jun 10 16:13:26 volumio volumio[1062]: [Vollibrespot] librespot_connect::discovery: Post "/" {}
Jun 10 16:13:26 volumio volumio[1062]: [Vollibrespot] : Connecting to AP "gew1-accesspoint-a-1jt9.ap.spotify.com:4070"
Jun 10 16:13:26 volumio volumio[1062]: [Vollibrespot] : Authenticated as "imaginarys" !
Jun 10 16:13:26 volumio volumio[1062]: [Vollibrespot] librespot_core::session: new Session[0]
Jun 10 16:13:26 volumio volumio[1062]: [Vollibrespot] librespot_connect::spirc: new Spirc[0]
Jun 10 16:13:26 volumio volumio[1062]: [Vollibrespot] librespot_core::mercury: new MercuryManager
Jun 10 16:13:26 volumio volumio[1062]: [Vollibrespot] librespot_playback::player: new Player[0]
Jun 10 16:13:26 volumio volumio[1062]: [Vollibrespot] : Using alsa sink
Jun 10 16:13:26 volumio volumio[1062]: [Vollibrespot] librespot_connect::spirc: input volume:65535 to mixer: 65535
Jun 10 16:13:26 volumio volumio[1062]: [Vollibrespot] vollibrespot::meta_pipe: Starting new MetaPipe[0]
Jun 10 16:13:26 volumio volumio[1062]: [Vollibrespot] : Metadata pipe established
Jun 10 16:13:26 volumio volumio[1062]: [Vollibrespot] librespot_core::session: Session[0] strong=5 weak=2
Jun 10 16:13:26 volumio volumio[1062]: [Vollibrespot] : Country: "FR"
Jun 10 16:13:26 volumio volumio[1062]: [Vollibrespot] vollibrespot::meta_pipe: Volume { volume_to_mixer: 65535 }
Jun 10 16:13:26 volumio volumio[1062]: [Vollibrespot] vollibrespot::meta_pipe: Event::Volume(100)
Jun 10 16:13:26 volumio volumio[934]: [SpotifyConnect] Volume: Sp:100 Volumio: 100
Jun 10 16:13:26 volumio volumio[934]: info: CoreStateMachine::pushState
Jun 10 16:13:26 volumio volumio[934]: info: CoreStateMachine::getState
Jun 10 16:13:26 volumio volumio[934]: info: CorePlayQueue::getTrack 0
Jun 10 16:13:26 volumio volumio[934]: info: CoreCommandRouter::volumioPushState
Jun 10 16:13:26 volumio volumio[934]: info: CoreCommandRouter::executeOnPlugin: volumiodiscovery , saveDeviceInfo
Jun 10 16:13:26 volumio sudo[2199]: volumio : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/sbin/ifconfig wlan0
Jun 10 16:13:26 volumio volumio[1062]: [Vollibrespot] librespot_core::mercury: unknown subscription uri=hm://remote/user/imaginarys/
Jun 10 16:13:26 volumio volumio[1062]: [Vollibrespot] librespot_core::mercury: subscribed uri=hm://remote/user/imaginarys/ count=0
Jun 10 16:13:26 volumio sudo[2199]: pam_unix(sudo:session): session opened for user root by (uid=0)
Jun 10 16:13:26 volumio sudo[2199]: pam_unix(sudo:session): session closed for user root
Jun 10 16:13:26 volumio volumio[1062]: [Vollibrespot] librespot_connect::spirc: kMessageTypeNotify "FRD-L09" d3df51889513473d556109dfa62d2231ce823e1c 1110078962 1560183206684
Jun 10 16:13:26 volumio volumio[1062]: [Vollibrespot] librespot_connect::spirc: kMessageTypeLoad "PC-CREATIS-MART" 4d16a046eb4e99fe4721728bd02377c0d404d312 1110079187 1560183206684
Jun 10 16:13:26 volumio volumio[1062]: [Vollibrespot] librespot_connect::spirc: Requesting API access token
Jun 10 16:13:26 volumio volumio[1062]: [Vollibrespot] vollibrespot::meta_pipe: SessionActive { became_active_at: 1560183206921 }
Jun 10 16:13:26 volumio volumio[1062]: [Vollibrespot] : SessionActive!
Jun 10 16:13:26 volumio volumio[1062]: [Vollibrespot] librespot_connect::spirc: Frame has 12 tracks
Jun 10 16:13:26 volumio volumio[1062]: [Vollibrespot] : Skipping track "spotify:episode:1buF0q7ExjTRDuuP2Qsr1W" at position [10] of 12
Jun 10 16:13:26 volumio volumio[1062]: [Vollibrespot] : Skipping track "spotify:episode:3HBD77zJZfr28us3L1OjGG" at position [11] of 12
Jun 10 16:13:26 volumio volumio[1062]: [Vollibrespot] : Skipping track "spotify:episode:7CLyCDkVbBwlmLYeQ2Hyc8" at position [0] of 12

[...]

Jun 10 16:18:02 volumio volumio[1062]: [Vollibrespot] : Skipping track "spotify:episode:1buF0q7ExjTRDuuP2Qsr1W" at position [10] of 12
Jun 10 16:18:02 volumio volumio[1062]: [Vollibrespot] : Skipping track "spotify:episode:3HBD77zJZfr28us3L1OjGG" at position [11] of 12
Jun 10 16:18:02 volumio volumio[1062]: [Vollibrespot] : Skipping track "spotify:episode:7CLyCDkVbBwlmLYeQ2Hyc8" at position [0] of 12
Jun 10 16:18:02 volumio volumio[1062]: [Vollibrespot] : Skipping track "spotify:episode:2yGwJ5gsZUgcVHpFurpE92" at position [1] of 12
Jun 10 16:18:08 volumio volumio[934]: info: CALLMETHOD: system_controller system sendBugReport [object Object]
Jun 10 16:18:08 volumio volumio[934]: info: CoreCommandRouter::executeOnPlugin: system , sendBugReport
Jun 10 16:18:09 volumio sudo[2602]: volumio : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/sbin/iwconfig
Jun 10 16:18:09 volumio sudo[2602]: pam_unix(sudo:session): session opened for user root by (uid=0)
Jun 10 16:18:09 volumio sudo[2602]: pam_unix(sudo:session): session closed for user root
Jun 10 16:18:09 volumio sudo[2620]: volumio : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/bin/journalctl -p 7
Jun 10 16:18:09 volumio sudo[2620]: pam_unix(sudo:session): session opened for user root by (uid=0)

### PR DESCRIPTION
**Pull request by ashthespy**
Notable [changes](https://github.com/ashthespy/Vollibrespot/blob/master/CHANGELOG.md#018---2019-11-06):
- Add support for podcasts
- Autoplay similar songs when your music ends
- Small performance tweaks

Closes #238

### CODE REVIEW

**Comment by balbuze** [comment]
Hi ash! Thanks for the Pr. There is something that needs to be fix (not related to the update). When the plugin is disabled, it remains in memory and still send message such when the output is changed in Volumio. Something like a socket.off seems to be required. Any idea?

**Comment by ashthespy** [comment]
Do you mean when the ALSA output device is changed? I don't completely follow..

**Comment by balbuze** [comment]
Yes. Step to reproduce. Use the plugin, disable it and change output device in playback option of Volumio. Save. You'll see the plugin update message for the outout. I fixed a similar behaviour in an other plugin using socket.io by adding a socket.off in the 'onstop' section.

**Comment by ashthespy** [comment]
>Yes. Step to reproduce. Use the plugin, disable it and change output device in playback option of Volumio. Save. You'll see the plugin update message for the outout. I fixed a similar behaviour in an other plugin using socket.io by adding a socket.off in the 'onstop' section.

That sounds like a Volumio bug right - when you disable the plugin, it should also drop all listeners, I will take a look when I have time!

**Comment by ashthespy** [comment]
Opened up a new issue https://github.com/volumio/Volumio2/issues/1836 
`socket.off` wont work in our case, as we don't use the websocket client, but hook directly in with  `commandRouter.sharedVars.registerCallback`.  The pluginmanager ofcourse just calls the `onStop` method and moves on, so we need to disable these callbacks manually.

**Comment by balbuze** [comment]
It can't connect when shared device is activated. It even dosen't appears as a device in Spotify

**Comment by ashthespy** [comment]
@balbuze  Could you check if its broadcasting the mDNS service? I was having issues with my desktop client a while ago, while the Andorid app was working fine..

**Comment by balbuze** [comment]
I can't check now, but it was non ok from my smartphone Android and from my laptop Ubuntu.

**Comment by balbuze** [comment]
when multi user disabled :
`Nov 08 19:40:44 volumio-rpi4 sudo[4767]: volumio : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/sbin/ifconfig wlan0
Nov 08 19:40:44 volumio-rpi4 volumio[4763]: vollibrespot v0.1.8 0b7ed39 2019-11-06 (librespot f67905a 2019-11-05) -- Built On 2019-11-06
Nov 08 19:40:44 volumio-rpi4 sudo[4767]: pam_unix(sudo:session): session opened for user root by (uid=0)
Nov 08 19:40:44 volumio-rpi4 volumio[1337]: [SpotifyConnect] null
Nov 08 19:40:44 volumio-rpi4 sudo[4767]: pam_unix(sudo:session): session closed for user root
Nov 08 19:40:44 volumio-rpi4 volumio[1337]: info: Setting screensaver timeout to 120 seconds.
Nov 08 19:40:44 volumio-rpi4 volumio[4763]: [Vollibrespot] librespot_connect::discovery: Zeroconf server listening on 0.0.0.0:41245
Nov 08 19:40:44 volumio-rpi4 volumio[4763]: [Vollibrespot] : Failed to register IPv6 receiver: Os { code: 19, kind: Other, message: "No such device" }
Nov 08 19:40:44 volumio-rpi4 sudo[4781]: volumio : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/bin/systemctl start volspotconnect2.service
Nov 08 19:40:44 volumio-rpi4 sudo[4781]: pam_unix(sudo:session): session opened for user root by (uid=0)
Nov 08 19:40:44 volumio-rpi4 systemd[1]: Started Volspotconnect2 Daemon.
Nov 08 19:40:44 volumio-rpi4 sudo[4781]: pam_unix(sudo:session): session closed for user root
Nov 08 19:40:44 volumio-rpi4 volumio[1337]: [SpotifyConnect] Vollibrespot Daemon Started
Nov 08 19:40:44 volumio-rpi4 wpa_supplicant[1043]: wlan0: Failed to initiate sched scan
Nov 08 19:40:45 volumio-rpi4 volumio[1337]: [SpotifyConnect] Internal Server Error
`

**Comment by ashthespy** [comment]
I will take, a look I think I have an idea - don't release yet!

**Comment by balbuze** [comment]
:+1:

**Pull request merged**
