### PR TITLE
Metadata support for Volspotconnect2

### PR DESCRIPTION
**Pull request by ashthespy**
Initial support with my modified version of librespot-https://github.com/ashthespy/librespot

Will look into making it prettier and ~~getting in the cover art later~~, but this should let you test as well.

### TODO
- [x] Cover art
- [x] Track duration
- [ ] Seek/track position update

### In the near future
- [ ] Alsa volume/Mixer support 
- [x] Bidirectional control

### CODE REVIEW

**Comment by ashthespy** [comment]
https://github.com/ashthespy/volumio-plugins/commit/b3b16f84527ae4d845f8cdfbbdd682b13091171d

Cheers!

**Comment by cortegedusage** [comment]
I think i am going to cry...
This definetely is beyond awesome

Op 28 feb. 2018 7:47 p.m. schreef "Ash" <notifications@github.com>:

**Comment by cortegedusage** [comment]
May I suggest clearing the playlist upon play, this makes the transition
between songs much cleaner in the web ui i think...

Op 28 feb. 2018 7:53 p.m. schreef "Dennis van Paassen" <dvpaassen@gmail.com

**Comment by ashthespy** [comment]
Unfortunately my annoyance with the entire volumio-plugins being one repo has taken over:

https://github.com/ashthespy/volumio-plugins/commit/b3b16f84527ae4d845f8cdfbbdd682b13091171d

@balbuze pretty please lets start a separate repo? :heart_eyes_cat:

**Comment by ashthespy** [comment]
> May I suggest clearing the playlist upon play, this makes the transition between songs much cleaner in the web ui i think...

That might be a good idea - let me give it a go :-)

**Comment by ashthespy** [comment]
`seek` support : https://github.com/ashthespy/volumio-plugins/commit/9722ff7b8d2138514cdb9a19ad81f484f52181ba

**Pull request merged**
